import type { Metadata } from "next";
import { Nunito, Nunito_Sans as NunitoSans } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["400", "600", "700"], // choisis les graisses que tu veux
  variable: "--font-nunito",
});
const nunitoSans = NunitoSans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-nunito-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={` ${nunito.variable} ${nunitoSans.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
